---
title: Principles and Governance
---

## Statement of Collaboration

Members involved in CCRCN collaborations are entitled to their own intellectual property, and distinctions should be made clarifying what is individual property versus group property. Here are the principles to which the Soil Carbon working group adheres to:

- Anything developed as a group is collective intellectual property (IP) that members collectively decide what to do with (such as assigning a creative commons license or signing rights over to a publisher).
- Anything developed outside the group is the intellectual property of the individual who produced it or their institution (whichever is applicable).
- Any outside IP needs to be properly acknowledged and cited in CCRCN work.
- All members agree not to share unpublished work outside the group without explicit permission to do so.
- At the end of the project, working group members commit to making code and derivative data products that the group developed collectively open and available as part of data releases associated with papers and reports.
- The working group will publish products that only include data that is or will be publicly available (via repository) at the time of working group publication.

## Code of Conduct

The Coastal Carbon Research Coordination Network (CCRCN) is dedicated to
providing a welcoming and supportive environment for all people,
regardless of background or identity. However, we recognize that some
groups in our community are subject to historical and ongoing
discrimination, and may be vulnerable or disadvantaged. Membership in
such a specific group can be on the basis of characteristics such as
gender, sexual orientation, disability, physical appearance, body size,
race, nationality, sex, color, ethnic or social origin, pregnancy,
citizenship, familial status, veteran status, genetic information,
religion or belief, political or any other opinion, membership of a
national minority, property, birth, age, or choice of text editor. We do
not tolerate harassment of participants on the basis of these
categories, or for any other reason.

Harassment is any form of behavior intended to exclude, intimidate, or
cause discomfort. Because we are a diverse community, we may have
different ways of communicating and of understanding the intent behind
actions. Therefore we have chosen to prohibit certain forms of behavior
in our community, regardless of intent. Prohibited harassing behavior
includes but is not limited to:

-   written or verbal comments which have the effect of excluding people
    on the basis of membership of a specific group listed above
-   causing someone to fear for their safety, such as through stalking,
    following, or intimidation
-   the display of sexual or violent images
-   unwelcome sexual attention
-   non-consensual or unwelcome physical contact
-   sustained disruption of talks, events or communications
-   incitement to violence, suicide, or self-harm
-   continuing to initiate interaction (including photography or
    recording) with someone after being asked to stop
-   publication of private communication without consent

Behavior not explicitly mentioned above may still constitute harassment.
The list above should not be taken as exhaustive but rather as a guide
to make it easier to enrich all of us and the communities in which we
participate. All CCRCN interactions should be professional regardless of
location: harassment is prohibited whether it occurs on- or offline, and
the same standards apply to both.

Enforcement of the Code of Conduct will be respectful and not include
any harassing behaviors. Any changes to the meaning of this Code of
Conduct must be approved by majority vote of the CCRCN Steering
Committee. CCRCN working group and network members will be informed of
these changes and any concerns that are raised will be discussed by the
Steering Committee.

Thank you for helping make this a welcoming, friendly community for all.

*This code of conduct is a modified version of that used by The
Carpentries, which was a modified version of that used by PyCon, which
in turn is forked from a template written by the Ada Initiative and
hosted on the Geek Feminism Wiki. Contributors to this document: Adam
Obeng, Aleksandra Pawlik, Bill Mills, Carol Willing, Erin Becker, Hilmar
Lapp, Kara Woo, Karin Lagesen, Pauline Barmby, Sheila Miguez, Simon
Waldman, Tracy Teal.*
