---
title: Data Contribution
---

### Why contribute data?

-   **It will increase the likelihood that your data will be included in future syntheses.** This means more citations, more collaborations, and more publicity of your work. We can also advertise your data to the community through the Coastal Carbon Atlas.
-   **The CCRCN is nested under the Smithsonian, a trusted institution with a legacy of long-term archival.** The Smithsonian has a long history of archiving physical and digital content, as well as high visibility and recognition. Submitting data to the CCRCN will enable you to release your dataset as a distinct DOI, which can be embargoed and versioned, and is stored under one of the Smithsonian Library's digital repositories (the default is Figshare).
-   **Our data clearinghouse is targeted to the coastal carbon community and receptive to feedback.** Because our focus is specialized, as opposed to a more general data repository, our vocabulary and structure is catered to those engaged in coastal carbon science, and we have the capability to quickly respond to new developments and recommendations through our version-controlled data structure.
-   **We have full-time staff dedicated to assisting the data carpentry and archival process.** Our staff are happy to assist the process of reformatting data and providing the affiliated licensing and DOI for your data release.
-   **You decide when and how the data are released to the public.** By establishing an embargo on a data submission, we can ensure that the data are not made public before a certain date, or until you have published with them. Although our default data repository is the research-orientated Figshare, we are able to assist with data releases that will be deposited in other locations, such as a data bank designated by your funding sources.

### Interested in contributing data?

Please email [CoastalCarbon\@si.edu](mailto:CoastalCarbon@si.edu) and CCRCN personnel will assist you in the process. Data submissions can remain embargoed for a time specified by the submitter. In embargo cases a data release will be prepared and shared with the submitter via a private dropbox link, until the embargo period ends, the data release is made public, and the dataset is drawn into synthesis products.

If you're interested in using our data templates, please visit this link to download.