---
title: Data Use and Responsibility
---

CCN is committed to treating data responsibly and providing credit to the authors who worked hard to collect, perform QAQC, etc. 

Download the Coastal Carbon Network's data responsibility agreement:

```{r echo=FALSE, warning=FALSE}
library(downloadthis)

## One file example
download_file(
  path = "downloads/CCN_Data_Responsibility_20190308.pdf",
  output_name = "CCN_Data_Responsibility_Agreement",
  button_label = "Download Me",
  button_type = "info",
  has_icon = TRUE,
  icon = "fa fa-save",
  self_contained = FALSE
)

# other examples
# https://fmmattioni.github.io/downloadthis/articles/downloadthis.html
```


## Citing CCN Data

We refer to users as anyone using either data we curate, or synthesis products we create. Data that is curated, but not created, by the Network, should not be attributed to the Network. Users should cite all dataset DOIs and credit the datasets’ original authors. All synthesis products created by the Network and associated collaborators will be listed under a Creative Commons With Attribution license. The Network should be acknowledged and cited appropriately if users utilize any of the data structures, tools, or scripts developed by Network and associated collaborators. We will develop additional tools to assist users in generating lists of citations, but users will be ultimately responsible for correctly citing all data used.

### How do I cite data downloaded from the Atlas?

Data downloaded from the Atlas will include a bibliography tailored to the dataset you have downloaded. Please cite the original data publications as well as the Coastal Carbon Network.

### How to cite the Coastal Carbon Network

Database citation in progress. Licensing is listed under the [Creative Commons BY 4.0](https://creativecommons.org/licenses/by/4.0/).
